gap = 8
margin = 4
# default_profile = "unity"

[profile.unity]
process = "Unity"
layout = "grid"
sort = "title"
columns = 2
gap = 12

[[profile.unity.slot]]
title = "Server"
position = 0

[[profile.unity.slot]]
title = "Client-01"
position = 1

[profile.browser]
process = "Google Chrome"
layout = "grid"
sort = "title"

[[ignore]]
type = "process"
value = "Calculator"
